### PR TITLE
Update all dependencies and loosen dependency ranges.

### PR DESCRIPTION
**Pull request by mohe2015**
This lets `cargo audit` pass.

Not tested well yet.

### CODE REVIEW

**Comment by Joining7943** [comment]
Thanks for your contribution!

A run of `cargo audit` shows:

```
❯ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 562 security advisories (from /home/lenny/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (83 crate dependencies)
Crate:     atty
Version:   0.2.14
Warning:   unsound
Title:     Potential unaligned read
Date:      2021-07-04
ID:        RUSTSEC-2021-0145
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0145
Dependency tree:
atty 0.2.14
├── env_logger 0.9.3
│   └── iai-callgrind-runner 0.6.1
│       └── iai-callgrind 0.6.1
│           └── benchmark-tests 0.1.0
└── colored 2.0.0
    └── iai-callgrind-runner 0.6.1

warning: 1 allowed warning found
```

This crate isn't affected by this `atty` vulnaribility because it doesn't run on windows hosts. That's a limitation of `valgrind`. So, instead of loosen all dependencies, I would suggest adding an audit configuration file ignoring this warning, maybe with a comment in it explaining why it is ignored.

I like the idea having an audit run in the ci. Would you mind creating a ci job running parallel to the `deny` job? Some of the dependency versions don't need to be that tight but, for now, I want to keep the MSRV of `1.60.0`. So, if you would just change the ones which wouldn't cause a MSRV version bump, would be great!

**Comment by Joining7943** [comment]
I just noticed that a separate job for `cargo audit` isn't necessary since the `deny` job already checks for vulnerabilities. Adding an ignore for this advisory in the `deny.toml` would also be ok, I guess.

**Comment by Joining7943** [comment]
Your work isn't lost but needs a rebase. Since `v0.6.0` The `iai-callgrind` package was wrongly using all dependencies of the `iai-callgrind-runner`, what has been fixed now. Also, I've added a ci job for running a check on the minimal versions of the dependencies as specified in the `Cargo.toml`.

**Comment by mohe2015** [comment]
Thanks for the good fixes and no worries, it was not much work and just a quick fix. I totally forgot about MSRV. I think I will leave the dependency updating up to you and you also seem to have activated dependabot.

I really love this tool, great work!

**Pull request closed without merging**
